import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}

const Navbar = () => {
  return (
    <nav className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50">
      <ul className="flex items-center gap-6 px-6 py-3 bg-white/30 backdrop-blur-md shadow-xl rounded-full border border-white/40">
        <li>
          <Link
            href="/overview"
            className="text-sm font-medium transition-transform duration-200 hover:scale-110"
          >
            Overview
          </Link>
        </li>
        <li>
          <Link
            href="/"
            className="text-sm font-medium transition-transform duration-200 hover:scale-110"
          >
            Home
          </Link>
        </li>
        <li>
          <Link
            href="/form"
            className="text-sm font-medium transition-transform duration-200 hover:scale-110"
          >
            Form
          </Link>
        </li>
      </ul>
    </nav>
  );
};

